language: python
sudo: false
os:
  - linux
  - osx

dist: trusty
# installs MacOS 10.13 - newer versions breaking python
osx_image: xcode9.3

before_install:
  - set -x
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if ! which python$TRAVIS_PYTHON_VERSION; then
        HOMEBREW_NO_AUTO_UPDATE=1 brew tap minrk/homebrew-python-frameworks
        HOMEBREW_NO_AUTO_UPDATE=1 brew cask install python-framework-${TRAVIS_PYTHON_VERSION/./}
      fi
      python3 -m pip install virtualenv
      python3 -m virtualenv -p $which python$(TRAVIS_PYTHON_VERSION) ~/travis-env
      source ~/travis-env/bin/activate
      python --version
    fi
  - export MPLBACKEND='Agg'
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - export MINICONDA_PREFIX="$HOME/miniconda"
  - bash miniconda.sh -b -p $MINICONDA_PREFIX
  - export PATH="$MINICONDA_PREFIX/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
install:
  - wget -q https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml
  - conda env create -q -n test-env --file qiime2-latest-py36-linux-conda.yml
  - source activate test-env
  - conda install -q pytest-cov
  - pip install -q flake8 coveralls
  - pip install -q https://github.com/qiime2/q2lint/archive/master.zip
  - make install
script:
  - make lint
  - make test-cov
after_success:
- coveralls
