{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-diversity-lib
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - biom-format {{ biom_format }}
    - decorator
    # Inherit global hard pin
    - hdf5 {{ hdf5 }}
    - numpy
    - pandas {{ pandas }}
    - psutil
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - scikit-bio {{ scikit_bio }}
    - scipy
    - unifrac >=0.20.0

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - pytest

  imports:
    - q2_diversity_lib
    - qiime2.plugins.diversity_lib

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
