{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-diversity-lib
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - biom-format >=2.1.5,<2.2.0
    - decorator
    - pandas
    - psutil
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*
    - scikit-bio
    - unifrac

test:
  imports:
    - q2_diversity_lib
    - qiime2.plugins.diversity_lib

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
