name: lint-build-test
# build on every PR and commit to master
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  debug:
    runs-on: macos-latest
    steps:
    - name: set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psutil
    - name: DEBUG PSUTIL
      run: |
        python -c "import psutil; print('logical==True', psutil.cpu_count(logical=True))"
        python -c "import psutil; print('logical==False', psutil.cpu_count(logical=False))"
 
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: lint
      run: |
        pip install -q https://github.com/qiime2/q2lint/archive/master.zip
        q2lint
        pip install -q flake8
        flake8

  build-and-test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # for versioneer
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - uses: qiime2/action-library-packaging@alpha1
      with: 
        plugin-name: q2-diversity-lib
        additional-tests: pytest --pyargs q2_diversity_lib
